language: node_js
node_js:
    - 12
branches:
    only:
        - master
cache: npm
install:
    - npm install --prefix client
    - npm install -g gulp-cli
script:
    - gulp --cwd client
    - echo "r.dve.tw" > client/build/CNAME
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local-dir: client/build
    on:
        branch: master
