language: node_js
node_js:
    - 10
branches:
    only:
        - master
cache: npm
install:
    - npm install --prefix client && npm install -g gulp-cli
script:
    - gulp --cwd client build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local-dir: dashboard/public
    on:
        branch: master
